config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show]
  resources :maps
  resources :tweets do
    
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  root 'tweets#index'


  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/map.rb
class Map < ApplicationRecord
    geocoded_by :address
    after_validation :geocode
end

app/models/tweet.rb
class Tweet < ApplicationRecord

    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
   
    has_many :comments, dependent: :destroy
   
   
    has_one_attached :image_top
  has_many_attached :images

  mount_uploader :image, ImageUploader
 # Active Storageのバリデーション
  validates :image_top, :images, content_type: { in: %w[image/jpeg image/gif image/png],
                                   message: "must be a valid image format" },
                                size: { less_than: 5.megabytes,    
                                        message: "should be less than 5MB" }

                                        
 # image_top のリサイズ済み画像を返す
  def resize_image_top
    image_top.variant(resize_to_limit: [500, 200])
  end

end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, 
  :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
  mount_uploader :image, ImageUploader
  has_many :tweets, dependent: :destroy#追記 ユーザーが削除されたら、ツイートも削除されるようになります。すでに書いてある場合は追記しなくて大丈夫です。
  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
      # サインアップ時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      # アカウント編集の時にnameとprofileのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
    protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      tweet = Tweet.find(params[:tweet_id])
      comment = tweet.comments.build(comment_params) 
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) 
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) 
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
      
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
    
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
    def index
        @maps = Map.all
        @map = Map.new
    end

    def create
        map = Map.new(map_params)
        if map.save
            redirect_to :action => "index"
        else
            redirect_to :action => "index"
        end
    end

    def destroy
        map = Map.find(params[:id])
        map.destroy
        redirect_to action: :index
    end

    private
    def map_params
    params.require(:map).permit(:address, :latitude, :longitude)
    end

    
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    before_action :set_tweet, only: [:update, :destroy, :show]
    
    def index
    
      if params[:search] == nil
        @tweets= Tweet.all
      elsif params[:search] == ''
        @tweets= Tweet.all
      else
      
        @tweets = Tweet.where("place LIKE ? ",'%' + params[:search] + '%')
      end

      @tweets = @tweets.page(params[:page]).per(5)
      @maps = Map.all
      @map = Map.new
    end
    
    
    
      def new
        @tweet = Tweet.new
      end
    
      def create
        @tweet = Tweet.new(tweet_params)
        @tweet.user_id = current_user.id 
        if @tweet.save
          redirect_to tweets_path, notice: 'Tweet was successfully created.'  # 適切なパスにリダイレクト
        else
          render :new
        end
      end
    

      def show
        @tweet = Tweet.find(params[:id])
        @comments = @tweet.comments
        @comment = Comment.new
       
      end
      
      def edit
        @tweet = Tweet.find(params[:id])
      end
      
      
      def update
        
        @tweet = Tweet.find(params[:id])
        if @tweet.update(tweet_params)
          redirect_to :action => "show", :id => tweet.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        @tweet = Tweet.find(params[:id])
        @tweet.destroy
        redirect_to action: :index


      end

    

      private

      def set_tweet
        @tweet = Tweet.find(params[:id])
      end

      def tweet_params
        params.require(:tweet).permit(:name, :date, :place, :genre, :organizer, :about, :lat, :lng, :address, :image_top, :images, :image)
      end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      end
      

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reina</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/0ba8fdf354.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <div class="a-title">
        <p>Farmers Market</p>
        <img src="https://loosedrawing.com/assets/illustrations/png/726.png" class="logo">

      </div>
      <div class="a-about">
        <% if user_signed_in? %>
          <li><%= link_to "Mypage >", user_path(current_user.id), class:"btn-new" %></li>
          <li><%= link_to 'Logout >', destroy_user_session_path, method: :delete, class: "btn-new" %></li>
          <li><%= link_to "New post>", new_tweet_path, class:"btn-new" %></li>

        <% else %>
          <li><%= link_to "Sign up >", new_user_registration_path, class: "btn-new" %></li>
          <li><%= link_to "Login >", new_user_session_path, class: "btn-new" %></li>
          <li><%= link_to "New post>", new_tweet_path, class:"btn-new" %></li>
        <% end %>
      </div>
       
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
    </footer>
  </body>
</html>

app/views/maps/index.html.erb
<h2>Google map</h2>

<input id="address" type="textbox" value="">
<input type="button" value="地図を検索" onclick="codeAddress()">
<div id="display">緯度経度が表示されるよ！</div>

<div id='map'></div>

<style>
    #map {
        height: 400px;
        width: 400px;
    }
</style>

<script>
    let map

    const display = document.getElementById('display')

    // mapの表示関数 
    function initMap() {
        geocoder = new google.maps.Geocoder()

        // mapの初期位置, 縮尺を定義
        map = new google.maps.Map(document.getElementById('map'), {
            center: {
                lat: 35.6458437,
                lng: 139.7046171
            },
            zoom: 12,
        });

        // mapsテーブルにあるそれぞれのレコードをmap上に表示 
        <% @maps.each do |m| %>
            (function(){
            var contentString = "住所：<%= m.address %>"; 

            // マーカーを立てる
            var marker = new google.maps.Marker({
                position:{lat: <%= m.latitude %>, lng: <%= m.longitude %>},
                map: map,
                title: contentString
            });

            // 情報ウィンドウ(吹き出し)の定義
            // 投稿の詳細ページへのリンクも
            var infowindow = new google.maps.InfoWindow({
            position: {lat: <%= m.latitude %>, lng: <%= m.longitude %>},
            content: "<a href='<%= map_url(m.id) %>' target='_blank'><%= m.address %></a>"
            });

            // クリックしたときに情報ウィンドウを表示
            marker.addListener('click', function() {
            infowindow.open(map, marker);
            });

            })();
        <% end %>
    }

    let geocoder

    // 地図検索関数
    function codeAddress() {
        let inputAddress = document.getElementById('address').value;

        geocoder.geocode({
            'address': inputAddress
        }, function (results, status) {
            if (status == 'OK') {
                map.setCenter(results[0].geometry.location);
                var marker = new google.maps.Marker({
                    map: map,
                    position: results[0].geometry.location
                });

            display.textContent = "検索結果：" + results[ 0 ].geometry.location
            } else {
                alert('該当する結果がありませんでした：' + status);
            }
        });
    }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= IzaSyBbWpjRd9zzKQqIb3lBxY0MpWhINkr9yvQ&callback=initMap"  async defer></script>

<h3>場所投稿フォーム</h3>
<%= form_for(@map, :url => { controller:'maps', action:'create'})do |f| %>

    <p>
    <%= f.label :address %>
    <%= f.text_field :address, size: "50x1" %>
    </p>

    <%= f.submit "送信"%>
<% end %>

<h3>場所一覧</h3>
<% @maps.each do |t| %>
    <p>住所 : <%= t.address %></p>
    <p>緯度 : <%= t.latitude %></p>
    <p>経度 : <%= t.longitude %></p>
    <p><%= link_to "削除する", map_path(t.id), method: :delete %></p>
    <hr>
<% end %>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
    <%= f.label :名前 %>
    <%= f.text_field :name, :size => 140 %> 
    <%= f.label :日付 %>
    <%= f.date_field :date, :size => 140 %> 
    <%= f.label :場所 %>
    <%= f.text_field :place, :size => 140 %> 
    <%= f.label :ジャンル %>
    <%= f.text_field :genre, :size => 140 %> 
    <%= f.label :主催者 %>
    <%= f.text_field :organizer, :size => 140 %> 
    <%= f.label :説明 %>
    <%= f.text_area :about, :size => 140 %> 
    
    <%= f.submit "編集する" %>
  <% end %>

app/views/tweets/index.html.erb
<div id="index">
  <div class="back">
  <div class="text-overlay">身近な所から地域に貢献しよう</div>
  </div>
  <div class="container">
    <div class="i-title">About Farmers Market</div>
    
    <p>ファーマーズマーケットとは？？</p>
    <p>地元の生産者が集まって食材を消費者に直売する市場のこと</p>
    <p>地域経済活性化や交流の場としての役割を果たす</p>
    

    <div class="image">
      <div class="image_wrap">
        <ul class="image_list image_list--left">
          <%= image_tag '1.jpg', :class=>"cat-icon" %>
          <%= image_tag '2.jpg', :class=>"cat-icon" %>
          <%= image_tag '3.jpg', :class=>"cat-icon" %>
          <%= image_tag '4.jpg', :class=>"cat-icon" %>
          <%= image_tag '5.jpg', :class=>"cat-icon" %>
          <%= image_tag '6.jpg', :class=>"cat-icon" %>
        </ul>
        <ul class="image_list image_list--left">
          <%= image_tag '1.jpg', :class=>"cat-icon" %>
          <%= image_tag '2.jpg', :class=>"cat-icon" %>
          <%= image_tag '3.jpg', :class=>"cat-icon" %>
          <%= image_tag '4.jpg', :class=>"cat-icon" %>
          <%= image_tag '5.jpg', :class=>"cat-icon" %>
          <%= image_tag '6.jpg', :class=>"cat-icon" %>
        </ul>
      </div>
    </div>
    <div class="body-container">
      <h3>Merits</h3>
      <h4>販売機会を増やせる<br>
      新規のお客さんを開拓できる<br>
      生産者同士での交流が生まれる</h4>
      <h5>地域の新鮮な商品が低価格で買える<br>
      顔を見ることができる安心・安全さ<br>
      地域経済に貢献できる</h5>
    </div>
  </div>

  <div class ="tweets">
    
      <div class="search">
        <h3>Post</h3>
        <%= form_tag({controller:"tweets", action:"index"}, method: :get, class: "search-form") do %>
          <%= text_area_tag :search, '', :size=>"60x3", class: "search-area" %>
          <%= submit_tag 'Search', class: "btn-new search-button" %>
        <% end %>
      </div>
     
   
      <div class="tweet">
     
      <% @tweets.each do |t| %>
        <div class="tweet_content">

        <div>Name:　　<%= t.name %></div>
        <div>Date:　　<%= t.date %></div>
        <div>Place:　　<%= t.place %></div>
        <div>Genre:   <%= t.genre %></div>
        <div>Organizer:　 <%= t.organizer %></div>
        <div>About:　　<%= t.about %></div>
        <div>Post_time  <%= t.created_at.strftime('%Y年%m月%d日 %H時%M分')%></div>
        <div><%= image_tag t.image_url, size: "300x300" if t.image? %></div>

        <div class="tweet-detail">
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
              <i class="fas fa-heart heart-icon"></i><%= t.likes.count %>
            <% end %>
          <% else %>
            <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :tweet do %>
              <i class="fas fa-heart heart-icon"></i><%= t.likes.count %>
            <% end %>
          <% end %>
        <% else %>
          <i class="fas fa-heart heart-icon"></i><%= t.likes.count %>
        <% end %>

          
        <%= link_to "Detail >", tweet_path(t.id), class:"btn-new" %> 
        <% if user_signed_in? && current_user.id == t.user_id %>
         
    
        <% end %>
              </div>
           
  </div>
      <% end %>
 
    



  </div>
      <div class="new">
  <%= link_to "New post>", new_tweet_path, class:"btn-new" %>
    </div>
    <div class="pagenate">
    <%= page_entries_info @tweets %>
    <%= paginate @tweets %>
</div>
</div>

app/views/tweets/new.html.erb
<div class="new-post">
<h3>New Post</h3>
<%= form_for @tweet do |f| %>
  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :name,  :size => 32 %>
  </div>
  <div class="field">
    <%= f.label :Date %><br>
    <%= f.date_field :date, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :Place %><br>
    <%= f.text_field :place, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :Genre %><br>
    <%= f.text_field :genre, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :Organizer %><br>
    <%= f.text_field :organizer, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :Contents %><br>
    <%= f.text_area :about, :size => "30x3" %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image, class:"btn-new" %>
  </div>
 
  <%= f.submit "Post", class: "btn-new" %>
  
  <script type="text/javascript">
    document.addEventListener("turbolinks:load", function() {
      document.getElementById("tweet_image_top").addEventListener("change", function() {
        var size_in_megabytes = this.files[0].size / 1024 / 1024;
        if (size_in_megabytes > 5) {
          alert("Maximum file size is 5MB. Please choose a smaller file.");
          this.value = "";
        }
      });
    });
  </script>
  
  



<% end %>

<%= stylesheet_link_tag 'new', :media => "all" %>

<div class="new_map">
  <%= form_with(model: @tweet,url: tweets_path, local: true) do |f| %>
    <div class="actions">
      <%= f.label :body,"内容" %>
      <%= f.text_field :body %>
      <%= f.label :lat,"緯度" %>
      <%= f.text_field :lat, :value =>"緯度", id: :lat %>
      <%= f.label :lng,"経度" %>
      <%= f.text_field :lng,:value =>"経度", id: :lng %>
      <%= f.submit %>
    </div>
  <% end %>



    <h2>Map</h2>
    <input id="address" type="textbox" value="GeekSalon">
    <input type="button" value="検索" onclick="codeAddress()">

    <div id='map'></div>
    <style>
      #map {
        height: 600px;
        width: 600px;
      }
    </style>
    <script>
      // 初期マップの設定
      let map
      let marker
      function initMap() {
        geocoder = new google.maps.Geocoder()

        map = new google.maps.Map(document.getElementById('map'), {
          center: { lat: 35.6803997, lng: 139.7690174 }, // 東京
          zoom: 15,
        });
      }
      // 検索後のマップ作成
      let geocoder;
      let aft;
      function codeAddress() {
        let inputAddress = document.getElementById('address').value;
        geocoder.geocode({ 'address': inputAddress }, function (results, status) {
          if (status == 'OK') {
            // マーカーが複数できないようにする
            if (aft == true) {
              marker.setMap(null);
            }
            // 新しくマーカーを作成する
            map.setCenter(results[0].geometry.location);
            marker = new google.maps.Marker({
              map: map,
              position: results[0].geometry.location,
              draggable: true // ドラッグ可能にする
            });
            // 二度目以降か判断
            aft = true;
            // 検索した時に緯度経度を入力する
            document.getElementById('lat').value = results[0].geometry.location.lat();
            document.getElementById('lng').value = results[0].geometry.location.lng();
            // マーカーのドロップ（ドラッグ終了）時のイベント
            google.maps.event.addListener(marker, 'dragend', function (ev) {
              // イベントの引数evの、プロパティ.latLngが緯度経度
              document.getElementById('lat').value = ev.latLng.lat();
              document.getElementById('lng').value = ev.latLng.lng();
            });
          } else {
            alert('該当する結果がありませんでした：' + status);
          }
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBbWpjRd9zzKQqIb3lBxY0MpWhINkr9yvQ&callback=initMap" async defer></script>
  
</div>

<%= link_to "Top page", tweets_path %>

</div>

app/views/tweets/show.html.erb
<div class="show">
<h1>Details</h1>


<div class="show_tweet">
 <%= image_tag @tweet.image_url, size: "500x500" if @tweet.image? %>
  <p>Name  :<%= @tweet.name %></p>
  <p>Date  :<%= @tweet.date %></p>
  <p>Place  :<%= @tweet.place %></p>
  <p>Genre  :<%= @tweet.genre %></p>
  <p>Organizer  :<%= @tweet.organizer %></p>
  <p>About  :<%= @tweet.about %></p>
 
  <p>post time  :<%= @tweet.created_at %></p>
  <% if user_signed_in? %>
      <% if current_user.already_liked?(@tweet) %>
        <%= link_to tweet_like_path(@tweet), method: :delete do %>
            <i class="fas fa-heart"></i><%= @tweet.likes.count %>
          
        <% end %>
      <% else %>
        <%= link_to tweet_likes_path(@tweet), method: :tweet do %>
            <i class="fas fa-heart heart-icon"></i><%= @tweet.likes.count %>
        <% end %>
      <% end %>
   <% else %>
    <i class="fas fa-heart heart-icon"></i><%= @tweet.likes.count %>
<% end %>

</div>
 
  <div class="image-top">
  <%= image_tag @tweet.resize_image_top if @tweet.image_top.attached? %>
  </div>


<%= link_to "編集する", edit_tweet_path(@tweet.id) %>

<div class="comment-wrapper">
  <p></p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "Top page >", tweets_path, class: "btn-new "%>
<%= link_to "Delete >", tweet_path(@tweet.id), method: :delete, class: "btn-new" %> 

 <!DOCTYPE html>
<html>
<head>
    <title>投稿の詳細</title>
    <style>
        /* 地図を表示する領域のスタイル */
        #map {
            height: 400px; /* 地図の高さ */
            width: 500px;   /* 地図の幅 */
        }
    </style>
</head>
<body>
    <!-- 地図を表示する領域 -->
    <div id="map"></div>

    <!-- Google Maps JavaScript API の読み込み -->

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBbWpjRd9zzKQqIb3lBxY0MpWhINkr9yvQ&callback=initMap" async defer></script>

    <script>
        // 地図を初期化する関数
        function initMap() {
            // 投稿された場所の緯度と経度（例として東京駅の座標）
            var postLocation = {lat: 35.681236, lng: 139.767125};
            
            // 地図を作成
            var map = new google.maps.Map(document.getElementById('map'), {
                center: postLocation, // 地図の初期表示位置
                zoom: 12 // ズームレベル (1 〜 20)
            });

            // マーカーを追加して投稿された場所を地図上に表示
            var marker = new google.maps.Marker({
                map: map,
                position: postLocation,
                title: '投稿された場所'
            });
        }
    </script>
</body>
</html>
        

</div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div id="u-show">
  <div class="user">
    Mypage
  </div>

  <div class="p">
    name : <%= @user.name %>
  </div>
  <div class="p">
    e-mail : <%= @user.email %>
  </div>
  <div class="p">
  profile : <%= @user.profile %>
</div>

  <% if current_user.id == @user.id %>
    <%= link_to "Edit", edit_user_registration_path %>
  <% end %>

  <h2>my post</h2>
  <% @user.tweets.each do |t| %>
 
  
  <% end %>

  <!-- 以下はいいね機能を実装している場合-->
  <h2>ユーザーがいいねした投稿一覧</h2>
  <% @user.liked_tweets.each do |t| %>
    <%= t.user.name %>
  <% end %>

  <%= link_to "Top-page >", tweets_path, class:"btn-new" %>
</div>